// Database types — generated by Supabase CLI after schema setup
// Run: npx supabase gen types typescript --project-id <id> > src/types/database.ts
export type Database = Record<string, never>; // Placeholder

// TelegramUser is available globally via telegram.d.ts ambient declarations
